apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dashboard

spec:
  replicas: 1

  selector:
    matchLabels:
      app: docker-dashboard

  template:
    metadata:
      labels:
        app: docker-dashboard

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: dashboard
          image: 834176180969.dkr.ecr.eu-north-1.amazonaws.com/docker-image-dashboard:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: ENVIRONMENT
              value: "Production"

            - name: DEPLOYMENT_TIME
              value: "Initial Deployment"
