apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dashboard

spec:
  replicas: 1

  selector:
    matchLabels:
      app: docker-dashboard

  template:
    metadata:
      labels:
        app: docker-dashboard

    spec:
      containers:
      - name: dashboard
        image: famaaaa04/docker-image-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        env:
        - name: ENVIRONMENT
          value: "Kubernetes"

        - name: DEPLOYMENT_TIME
          value: "Day-28"

        - name: IMAGE_TAG
          value: "v2"
